project_id = "mhsbjqoqljytyskgxckn"

[functions.process-book]
verify_jwt = false

[functions.generate-audio]
verify_jwt = false

[functions.translate-batch]
verify_jwt = false

[functions.translate-all]
verify_jwt = false

[functions.tts-preview]
verify_jwt = false
